// Auto-generated character data
const CHINESE_CHARACTERS = [
  { character: "是", pinyin: "shì", definition: "to be", frequency_rank: 1 },
  {
    character: "在",
    pinyin: "zài",
    definition: "at / in / on",
    frequency_rank: 2,
  },
  { character: "有", pinyin: "yǒu", definition: "to have", frequency_rank: 3 },
  {
    character: "了",
    pinyin: "le",
    definition: "(particle indicating change/completion)",
    frequency_rank: 4,
  },
  {
    character: "和",
    pinyin: "hé",
    definition: "and / with",
    frequency_rank: 5,
  },
  {
    character: "到",
    pinyin: "dào",
    definition: "to / until; arrive",
    frequency_rank: 6,
  },
  {
    character: "对",
    pinyin: "duì",
    definition: "to / toward; correct",
    frequency_rank: 7,
  },
  {
    character: "给",
    pinyin: "gěi",
    definition: "to / for; give",
    frequency_rank: 8,
  },
  { character: "去", pinyin: "qù", definition: "to go", frequency_rank: 9 },
  { character: "来", pinyin: "lái", definition: "to come", frequency_rank: 10 },
  {
    character: "要",
    pinyin: "yào",
    definition: "to want; need",
    frequency_rank: 11,
  },
  {
    character: "可以",
    pinyin: "kěyǐ",
    definition: "can / may",
    frequency_rank: 12,
  },
  { character: "从", pinyin: "cóng", definition: "from", frequency_rank: 13 },
  {
    character: "跟",
    pinyin: "gēn",
    definition: "with; follow",
    frequency_rank: 14,
  },
  {
    character: "看",
    pinyin: "kàn",
    definition: "to look / watch",
    frequency_rank: 15,
  },
  { character: "好", pinyin: "hǎo", definition: "good", frequency_rank: 16 },
  { character: "大", pinyin: "dà", definition: "big", frequency_rank: 17 },
  { character: "小", pinyin: "xiǎo", definition: "small", frequency_rank: 18 },
  {
    character: "多",
    pinyin: "duō",
    definition: "many / much",
    frequency_rank: 19,
  },
  {
    character: "少",
    pinyin: "shǎo",
    definition: "few / little",
    frequency_rank: 20,
  },
  { character: "很", pinyin: "hěn", definition: "very", frequency_rank: 21 },
  {
    character: "真",
    pinyin: "zhēn",
    definition: "really / truly",
    frequency_rank: 22,
  },
  {
    character: "吧",
    pinyin: "ba",
    definition: "(modal particle: suggestion/softening)",
    frequency_rank: 23,
  },
  { character: "吃", pinyin: "chī", definition: "to eat", frequency_rank: 24 },
  { character: "喝", pinyin: "hē", definition: "to drink", frequency_rank: 25 },
  {
    character: "喜欢",
    pinyin: "xǐhuān",
    definition: "to like",
    frequency_rank: 26,
  },
  {
    character: "想",
    pinyin: "xiǎng",
    definition: "to think / to want",
    frequency_rank: 27,
  },
  {
    character: "知道",
    pinyin: "zhīdào",
    definition: "to know",
    frequency_rank: 28,
  },
  {
    character: "学",
    pinyin: "xué",
    definition: "to study / learn",
    frequency_rank: 29,
  },
  { character: "买", pinyin: "mǎi", definition: "to buy", frequency_rank: 30 },
  {
    character: "等",
    pinyin: "děng",
    definition: "to wait",
    frequency_rank: 31,
  },

  {
    character: "门",
    pinyin: "mén",
    definition: "door; entrance",
    frequency_rank: 32,
  },
  { character: "水", pinyin: "shuǐ", definition: "water", frequency_rank: 33 },
  {
    character: "电",
    pinyin: "diàn",
    definition: "electricity / power",
    frequency_rank: 34,
  },
  { character: "路", pinyin: "lù", definition: "road", frequency_rank: 35 },
  {
    character: "站",
    pinyin: "zhàn",
    definition: "station; stop",
    frequency_rank: 36,
  },
  { character: "左", pinyin: "zuǒ", definition: "left", frequency_rank: 37 },
  { character: "右", pinyin: "yòu", definition: "right", frequency_rank: 38 },
  {
    character: "前",
    pinyin: "qián",
    definition: "front / ahead",
    frequency_rank: 39,
  },
  {
    character: "后",
    pinyin: "hòu",
    definition: "back / behind",
    frequency_rank: 40,
  },

  {
    character: "谢谢",
    pinyin: "xièxie",
    definition: "thank you",
    frequency_rank: 41,
  },
  { character: "请", pinyin: "qǐng", definition: "please", frequency_rank: 42 },
  {
    character: "抱歉",
    pinyin: "bàoqiàn",
    definition: "sorry",
    frequency_rank: 43,
  },
  {
    character: "没事",
    pinyin: "méishì",
    definition: "it's okay",
    frequency_rank: 44,
  },

  {
    character: "出口",
    pinyin: "chūkǒu",
    definition: "exit",
    frequency_rank: 45,
  },
  {
    character: "入口",
    pinyin: "rùkǒu",
    definition: "entrance",
    frequency_rank: 46,
  },
  {
    character: "厕所",
    pinyin: "cèsuǒ",
    definition: "toilet",
    frequency_rank: 47,
  },
  { character: "男", pinyin: "nán", definition: "male", frequency_rank: 48 },
  { character: "女", pinyin: "nǚ", definition: "female", frequency_rank: 49 },
  {
    character: "禁止",
    pinyin: "jìnzhǐ",
    definition: "prohibited",
    frequency_rank: 50,
  },
  { character: "停", pinyin: "tíng", definition: "stop", frequency_rank: 51 },
  {
    character: "开",
    pinyin: "kāi",
    definition: "open / on",
    frequency_rank: 52,
  },
  {
    character: "关",
    pinyin: "guān",
    definition: "close / off",
    frequency_rank: 53,
  },
  { character: "票", pinyin: "piào", definition: "ticket", frequency_rank: 54 },
  {
    character: "楼",
    pinyin: "lóu",
    definition: "building / floor",
    frequency_rank: 55,
  },
  {
    character: "医院",
    pinyin: "yīyuàn",
    definition: "hospital",
    frequency_rank: 56,
  },
  {
    character: "学校",
    pinyin: "xuéxiào",
    definition: "school",
    frequency_rank: 57,
  },
  {
    character: "银行",
    pinyin: "yínháng",
    definition: "bank",
    frequency_rank: 58,
  },
  {
    character: "公司",
    pinyin: "gōngsī",
    definition: "company",
    frequency_rank: 59,
  },
  {
    character: "商店",
    pinyin: "shāngdiàn",
    definition: "shop / store",
    frequency_rank: 60,
  },

  {
    character: "地铁",
    pinyin: "dìtiě",
    definition: "subway",
    frequency_rank: 61,
  },
  {
    character: "公交",
    pinyin: "gōngjiāo",
    definition: "bus (public transport)",
    frequency_rank: 62,
  },
  {
    character: "的士",
    pinyin: "díshì",
    definition: "taxi",
    frequency_rank: 63,
  },
  {
    character: "火车",
    pinyin: "huǒchē",
    definition: "train",
    frequency_rank: 64,
  },
  {
    character: "飞机",
    pinyin: "fēijī",
    definition: "airplane",
    frequency_rank: 65,
  },
  { character: "地图", pinyin: "dìtú", definition: "map", frequency_rank: 66 },

  {
    character: "饭",
    pinyin: "fàn",
    definition: "rice / meal",
    frequency_rank: 67,
  },
  {
    character: "菜",
    pinyin: "cài",
    definition: "dish / cuisine",
    frequency_rank: 68,
  },
  {
    character: "面",
    pinyin: "miàn",
    definition: "noodles",
    frequency_rank: 69,
  },
  { character: "汤", pinyin: "tāng", definition: "soup", frequency_rank: 70 },
  { character: "肉", pinyin: "ròu", definition: "meat", frequency_rank: 71 },
  { character: "鱼", pinyin: "yú", definition: "fish", frequency_rank: 72 },
  { character: "鸡", pinyin: "jī", definition: "chicken", frequency_rank: 73 },
  {
    character: "牛",
    pinyin: "niú",
    definition: "beef / cow",
    frequency_rank: 74,
  },
  {
    character: "蔬菜",
    pinyin: "shūcài",
    definition: "vegetables",
    frequency_rank: 75,
  },
  {
    character: "水果",
    pinyin: "shuǐguǒ",
    definition: "fruit",
    frequency_rank: 76,
  },
  { character: "茶", pinyin: "chá", definition: "tea", frequency_rank: 77 },
  {
    character: "啤酒",
    pinyin: "píjiǔ",
    definition: "beer",
    frequency_rank: 78,
  },
  { character: "辣", pinyin: "là", definition: "spicy", frequency_rank: 79 },
  {
    character: "冰",
    pinyin: "bīng",
    definition: "ice / cold (drinks)",
    frequency_rank: 80,
  },

  { character: "好", pinyin: "hǎo", definition: "good", frequency_rank: 81 },
  { character: "坏", pinyin: "huài", definition: "bad", frequency_rank: 82 },
  { character: "快", pinyin: "kuài", definition: "fast", frequency_rank: 83 },
  { character: "慢", pinyin: "màn", definition: "slow", frequency_rank: 84 },
  { character: "热", pinyin: "rè", definition: "hot", frequency_rank: 85 },
  { character: "冷", pinyin: "lěng", definition: "cold", frequency_rank: 86 },
  {
    character: "贵",
    pinyin: "guì",
    definition: "expensive",
    frequency_rank: 87,
  },
  {
    character: "便宜",
    pinyin: "piányi",
    definition: "cheap",
    frequency_rank: 88,
  },
  {
    character: "一点",
    pinyin: "yīdiǎn",
    definition: "a little; a bit",
    frequency_rank: 89,
  },

  {
    character: "登录",
    pinyin: "dēnglù",
    definition: "log in",
    frequency_rank: 90,
  },
  {
    character: "用户",
    pinyin: "yònghù",
    definition: "user",
    frequency_rank: 91,
  },
  {
    character: "密码",
    pinyin: "mìmǎ",
    definition: "password",
    frequency_rank: 92,
  },
  {
    character: "确认",
    pinyin: "quèrèn",
    definition: "confirm",
    frequency_rank: 93,
  },
  {
    character: "取消",
    pinyin: "qǔxiāo",
    definition: "cancel",
    frequency_rank: 94,
  },
  {
    character: "提交",
    pinyin: "tíjiāo",
    definition: "submit",
    frequency_rank: 95,
  },
  {
    character: "保存",
    pinyin: "bǎocún",
    definition: "save",
    frequency_rank: 96,
  },
  {
    character: "删除",
    pinyin: "shānchú",
    definition: "delete",
    frequency_rank: 97,
  },
  {
    character: "搜索",
    pinyin: "sōusuǒ",
    definition: "search",
    frequency_rank: 98,
  },
  {
    character: "帮助",
    pinyin: "bāngzhù",
    definition: "help",
    frequency_rank: 99,
  },
  {
    character: "设置",
    pinyin: "shèzhì",
    definition: "settings",
    frequency_rank: 100,
  },
];
